name: News Room Engine Cron

on:
  #schedule:
  #  - cron: '15,45 * * * *'
  workflow_dispatch: # Allows you to manually trigger the script with a button

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Codebase Pull
        uses: actions/checkout@v4  # Keeps tracking clean

      - name: Initialize Runtime Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Load Dependencies
        run: pip install -r requirements.txt

      - name: Execute News Engine
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          # Forces the runner to use the updated secure JavaScript runtime engine
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true" 
        run: python app.py
